// ==========================================
// GamePlayScreen Styles
// ==========================================

import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// Local colors for this screen (extends theme)
export const GAME_COLORS = {
    primary: '#09aa09',
    primaryDark: '#067a06',
    backgroundDark: '#102210',
    surfaceDark: '#1a331a',
    surfaceLighter: '#244224',
    cardBorder: 'rgba(255,255,255,0.1)',
    textPrimary: '#FFFFFF',
    textSecondary: '#9CA3AF',
    textSlate: '#6B7280',
    error: '#ef4444',
    warning: '#eab308',
    info: '#3b82f6',
    ponto: '#F97316',
    secondary: '#F97316',
    surfaceDarker: '#142814',
    success: '#22c55e',
};

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: GAME_COLORS.backgroundDark,
    },
    backgroundGlow: {
        position: 'absolute',
        top: '30%',
        left: '-10%',
        width: '120%',
        height: '40%',
        backgroundColor: 'rgba(9, 170, 9, 0.05)',
        borderRadius: 1000,
        transform: [{ scaleX: 1.5 }],
    },
    loadingContainer: {
        flex: 1,
        backgroundColor: GAME_COLORS.backgroundDark,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
    },
    loadingText: {
        color: GAME_COLORS.textSecondary,
        fontSize: 16,
    },
    safeArea: {
        flex: 1,
    },

    // HEADER
    header: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
    },
    scoreboardContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: 'rgba(26, 51, 26, 0.8)',
        borderRadius: 16,
        padding: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
    },
    playerSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
    },
    playerSectionRight: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    playerSectionReverse: {
        flexDirection: 'row-reverse',
    },
    avatarContainer: {
        position: 'relative',
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: GAME_COLORS.surfaceLighter,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
    },
    avatarMe: {
        borderColor: GAME_COLORS.primary,
    },
    avatarOpponent: {
        borderColor: 'rgba(239, 68, 68, 0.5)',
    },
    levelBadge: {
        position: 'absolute',
        bottom: -4,
        left: -4,
        backgroundColor: GAME_COLORS.primary,
        paddingHorizontal: 6,
        paddingVertical: 1,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: GAME_COLORS.surfaceDark,
    },
    levelBadgeOpponent: {
        position: 'absolute',
        bottom: -4,
        right: -4,
        backgroundColor: 'rgba(127, 29, 29, 0.8)',
        paddingHorizontal: 6,
        paddingVertical: 1,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: GAME_COLORS.surfaceDark,
    },
    levelText: {
        color: '#FFF',
        fontSize: 10,
        fontWeight: 'bold',
    },
    scoreText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: GAME_COLORS.textPrimary,
    },
    timerSection: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 8,
    },
    matchTimerText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: GAME_COLORS.textPrimary,
        fontFamily: 'monospace',
    },
    playerName: {
        fontSize: 11,
        color: GAME_COLORS.textSecondary,
        flexShrink: 1,
    },
    playerInfo: {
        flexShrink: 1,
    },
    playerInfoRight: {
        marginLeft: 0,
        marginRight: 8,
        alignItems: 'flex-end',
    },
    avatarTimerWrapper: {
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'center',
        width: 48,
        height: 48,
        flexShrink: 0,
    },
    timerRingSvg: {
        position: 'absolute',
    },

    // MAIN AREA
    mainArea: {
        flex: 1,
        flexDirection: 'column',
        paddingHorizontal: 8,
        paddingVertical: 8,
        justifyContent: 'space-between',
    },

    // DECK SIDEBARS
    deckSidebar: {
        width: 50,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    deckSidebarLeft: {
        width: 55,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    deckSidebarRight: {
        width: 55,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    deckCard: {
        width: 48,
        height: 64,
        backgroundColor: GAME_COLORS.surfaceLighter,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    // Player & Action Deck with Images
    deckCardContainer: {
        width: 52,
        aspectRatio: 2 / 3, // Standard card aspect ratio
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    deckCardContainerActive: {
        borderColor: GAME_COLORS.primary,
        borderWidth: 2,
        shadowColor: GAME_COLORS.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
        elevation: 8,
    },
    deckCardImage: {
        width: '100%',
        height: '100%',
        borderRadius: 6,
    },
    deckLabel: {
        position: 'absolute',
        bottom: -14,
        fontSize: 8,
        color: GAME_COLORS.textSlate,
        fontWeight: 'bold',
    },
    deckCardActive: {
        borderColor: GAME_COLORS.primary,
        borderWidth: 2,
        backgroundColor: 'rgba(9, 170, 9, 0.2)',
    },
    deckLabelActive: {
        color: GAME_COLORS.primary,
    },
    // Ponto Deck with Image
    pontoDeckCard: {
        width: 56,
        aspectRatio: 1, // Square like the original Ponto Back.png
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        opacity: 0.5,
    },
    pontoDeckCardActive: {
        borderColor: GAME_COLORS.ponto,
        borderWidth: 2,
        opacity: 1,
        shadowColor: GAME_COLORS.ponto,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
        elevation: 5,
    },
    pontoDeckImage: {
        width: '100%',
        height: '100%',
        borderRadius: 6,
    },
    drawsRemainingBadge: {
        backgroundColor: GAME_COLORS.primary,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
        marginTop: 4,
    },
    drawsRemainingText: {
        color: '#FFF',
        fontSize: 10,
        fontWeight: 'bold',
    },

    // CENTER ZONE
    centerZone: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    centerContent: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // FIELD
    fieldRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 4,
        paddingHorizontal: 4,
    },
    fieldSlot: {
        flex: 1,
        aspectRatio: 2 / 3,
        backgroundColor: GAME_COLORS.surfaceLighter,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fieldSlotSelected: {
        borderColor: GAME_COLORS.primary,
        borderWidth: 2,
    },
    fieldSlotAttacker: {
        borderColor: GAME_COLORS.primary,
        borderWidth: 2,
        shadowColor: GAME_COLORS.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 8,
        elevation: 8,
    },
    fieldSlotTarget: {
        borderColor: GAME_COLORS.error,
        borderWidth: 2,
    },
    cardBack: {
        flex: 1,
        width: '100%',
        backgroundColor: GAME_COLORS.surfaceLighter,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardBackCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.05)',
    },
    emptySlotCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.05)',
    },
    slotCardFilled: {
        flex: 1,
        width: '100%',
    },
    slotCardImage: {
        width: '100%',
        height: '100%',
    },
    opponentCardBackImage: {
        width: '100%',
        height: '100%',
        borderRadius: 6,
    },
    slotCardOverlay: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingVertical: 2,
        alignItems: 'center',
    },
    slotCardOverlaySelected: {
        backgroundColor: GAME_COLORS.primary,
    },
    slotCardStat: {
        fontSize: 8,
        fontWeight: 'bold',
        color: '#FFF',
    },
    attackerPing: {
        position: 'absolute',
        top: 4,
        right: 4,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: GAME_COLORS.primary,
    },

    phaseBadge: {
        position: 'absolute',
        top: 0,
        backgroundColor: 'rgba(0,0,0,0.4)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(9, 170, 9, 0.2)',
    },
    phaseBadgeText: {
        color: GAME_COLORS.primary,
        fontSize: 12,
        fontWeight: 'bold',
    },
    fieldCircle: {
        width: 140,
        height: 140,
        borderRadius: 70,
        borderWidth: 3,
        borderColor: 'rgba(255,255,255,0.1)',
        backgroundColor: 'rgba(22, 101, 52, 0.4)',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    fieldCircleInner: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fieldLine: {
        position: 'absolute',
        width: '100%',
        height: 2,
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    fieldDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: 'rgba(255,255,255,0.3)',
    },
    movesIndicator: {
        position: 'absolute',
        top: 40,
        flexDirection: 'row',
        gap: 4,
        zIndex: 25,
    },
    moveDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: GAME_COLORS.surfaceLighter,
    },
    moveDotActive: {
        backgroundColor: GAME_COLORS.primary,
    },
    battleDisplay: {
        position: 'absolute',
        bottom: -40,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.8)',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        gap: 12,
    },
    battleSide: {
        alignItems: 'center',
    },
    battleLabel: {
        color: GAME_COLORS.textSecondary,
        fontSize: 10,
        fontWeight: '600',
    },
    battleValue: {
        color: '#FFF',
        fontSize: 24,
        fontWeight: 'bold',
    },
    battleVs: {
        color: GAME_COLORS.warning,
        fontSize: 12,
        fontWeight: 'bold',
    },
    attackResult: {
        position: 'absolute',
        backgroundColor: GAME_COLORS.surfaceDark,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: GAME_COLORS.info,
    },
    attackResultGoal: {
        backgroundColor: 'rgba(9, 170, 9, 0.3)',
        borderColor: GAME_COLORS.primary,
    },
    attackResultText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 14,
    },

    // ACTION BUTTONS
    actionButtons: {
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: 4,
        marginTop: 8,
    },
    endTurnButton: {
        flex: 1,
        backgroundColor: GAME_COLORS.surfaceLighter,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        paddingVertical: 10,
        borderRadius: 12,
        alignItems: 'center',
    },
    endTurnText: {
        color: GAME_COLORS.textSlate,
        fontSize: 12,
        fontWeight: 'bold',
    },
    attackButton: {
        flex: 2,
        backgroundColor: GAME_COLORS.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 10,
        borderRadius: 12,
    },
    attackButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    defenseButton: {
        flex: 1,
        backgroundColor: GAME_COLORS.info,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
    },
    defenseButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    revealButton: {
        flex: 1,
        backgroundColor: GAME_COLORS.success,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
    },
    revealButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    drawPontoButton: {
        flex: 2,
        backgroundColor: GAME_COLORS.ponto,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
    },
    drawPontoText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    pontoCardDisplay: {
        position: 'absolute',
        top: -65,
        alignSelf: 'center',
        alignItems: 'center',
        zIndex: 30,
    },
    pontoCardImage: {
        width: 56,
        height: 56,
        borderRadius: 4,
        backgroundColor: GAME_COLORS.surfaceLighter,
    },
    pontoCardValue: {
        color: GAME_COLORS.ponto,
        fontSize: 10,
        fontWeight: 'bold',
        marginTop: 2,
        backgroundColor: 'rgba(0,0,0,0.8)',
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 4,
    },
    acceptGoalButton: {
        flex: 1,
        backgroundColor: GAME_COLORS.error,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
    },
    acceptGoalText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    endAttackButton: {
        flex: 1,
        backgroundColor: GAME_COLORS.warning,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
    },
    endAttackText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    buttonDisabled: {
        opacity: 0.5,
    },

    // HAND AREA
    handArea: {
        backgroundColor: GAME_COLORS.surfaceDark,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.05)',
        paddingTop: 8,
        paddingBottom: 24,
    },
    handDragIndicator: {
        width: 48,
        height: 4,
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 2,
        alignSelf: 'center',
        marginBottom: 8,
    },
    handHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginBottom: 8,
    },
    handCount: {
        fontSize: 12,
        color: GAME_COLORS.textSlate,
        fontWeight: '500',
    },
    handScroll: {
        paddingHorizontal: 16,
        gap: 12,
    },
    handCard: {
        width: 88,
        aspectRatio: 2 / 3,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: GAME_COLORS.surfaceLighter,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    handCardSelected: {
        borderColor: GAME_COLORS.primary,
        borderWidth: 2,
        marginTop: -8,
        marginBottom: 8,
    },
    handCardImage: {
        width: '100%',
        height: '100%',
    },
    handCardPlaceholder: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    handCardGradient: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '50%',
        backgroundColor: 'transparent',
    },
    positionBadge: {
        position: 'absolute',
        top: 4,
        left: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    positionBadgeText: {
        color: '#FFF',
        fontSize: 10,
        fontWeight: 'bold',
    },
    handCardRating: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFF',
    },
    handCardName: {
        position: 'absolute',
        bottom: 8,
        left: 8,
        fontSize: 10,
        color: 'rgba(255,255,255,0.6)',
    },
    handCardActionLabel: {
        position: 'absolute',
        bottom: 8,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: GAME_COLORS.warning,
        fontSize: 10,
        fontWeight: 'bold',
        textShadowColor: 'rgba(0,0,0,0.8)',
        textShadowRadius: 2,
    },
    handCardPontoLabel: {
        position: 'absolute',
        bottom: 8,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: GAME_COLORS.secondary,
        fontSize: 10,
        fontWeight: 'bold',
        textShadowColor: 'rgba(0,0,0,0.8)',
        textShadowRadius: 2,
    },

    // ACTION MODAL
    actionModalContent: {
        width: '85%',
        backgroundColor: GAME_COLORS.surfaceDarker,
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: GAME_COLORS.cardBorder,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    actionModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: GAME_COLORS.textPrimary,
        marginBottom: 16,
    },
    actionCardPreview: {
        width: 100,
        height: 140,
        backgroundColor: GAME_COLORS.surfaceLighter,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: GAME_COLORS.warning,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    actionCardPreviewName: {
        color: GAME_COLORS.warning,
        marginTop: 8,
        fontWeight: 'bold',
    },
    actionModalDesc: {
        fontSize: 16,
        color: GAME_COLORS.textSecondary,
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 22,
    },
    actionModalButtons: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    actionUseButton: {
        flex: 1,
        backgroundColor: GAME_COLORS.warning,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    actionCancelButton: {
        flex: 1,
        backgroundColor: GAME_COLORS.surfaceLighter,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    actionButtonText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 16,
    },

    // DRAW PHASE MODAL
    drawPhaseModal: {
        width: '90%',
        backgroundColor: GAME_COLORS.surfaceDarker,
        borderRadius: 20,
        padding: 24,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: GAME_COLORS.primary,
        gap: 16,
    },
    drawPhaseTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#FFF',
        marginTop: 8,
    },
    drawPhaseSubtitle: {
        fontSize: 14,
        color: GAME_COLORS.textSecondary,
        marginBottom: 8,
    },
    drawOptionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: GAME_COLORS.surfaceLighter,
        borderRadius: 16,
        padding: 16,
        width: '100%',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        gap: 16,
    },
    drawOptionIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    drawOptionTextContainer: {
        flex: 1,
    },
    drawOptionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFF',
        marginBottom: 4,
    },
    drawOptionDesc: {
        fontSize: 12,
        color: GAME_COLORS.textSlate,
    },

    // OTHER MODALS & LABELS
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    menuModal: {
        backgroundColor: GAME_COLORS.surfaceDark,
        borderRadius: 16,
        padding: 16,
        width: 200,
        gap: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 10,
    },
    menuItemText: {
        color: GAME_COLORS.textPrimary,
        fontSize: 15,
    },
    menuItemDanger: {
        color: GAME_COLORS.error,
        fontSize: 15,
    },
    gameEndModal: {
        backgroundColor: GAME_COLORS.surfaceDark,
        borderRadius: 20,
        padding: 24,
        alignItems: 'center',
        width: 280,
        gap: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    gameEndTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: GAME_COLORS.textPrimary,
    },
    gameEndReason: {
        fontSize: 14,
        color: GAME_COLORS.textSecondary,
        textAlign: 'center',
    },
    gameEndButton: {
        backgroundColor: GAME_COLORS.primary,
        paddingHorizontal: 32,
        paddingVertical: 12,
        borderRadius: 12,
        marginTop: 8,
    },
    gameEndButtonText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 16,
    },
});
